import { NotificationType } from './types.ts';
import {
  AnnaImage,
  EarthImage,
  ShieldImage,
  TransferImage,
} from '@assets/images';

export const NOTIFICATIONS: NotificationType[] = [
  {
    id: 1,
    date: 'Today, 17 June',
    receivedImage: AnnaImage,
    receivedTitle: 'Received from Anna',
    receivedSum: '+$110',
    receivedCard: 'Debit •• 4385',
    receivedTotalSum: '$4,098.12',
    receivedDate: '17 June 2025, 17:49',
    receivedType: 'Payments',
    isOnline: true,
  },
  {
    id: 2,
    date: 'Yesterday, 16 June',
    receivedImage: EarthImage,
    receivedTitle: 'See our limited offer!',
    subTitle: 'Would you like to visit new countries? Maybe it’s your time!',
    receivedDate: '16 June 2025, 23:08',
    receivedType: 'Travel',
    sentImage: TransferImage,
    sentTitle: 'Sent to •• 2041',
    sentSum: '-$14.62',
    sentCard: 'Debit •• 4385',
    sentTotalSum: '$3,987.5',
    sentDate: '16 June 2025, 06:18',
    sentType: 'Payments',
  },
  {
    id: 3,
    date: '24 March, 2025',
    receivedImage: ShieldImage,
    receivedTitle: 'New login into account',
    subTitle:
      'You have logged in from a new location:\niOS 26.0.1 · 109.255.84.7 · Spain',
    receivedDate: '24 March 2025, 15:44',
    receivedType: 'Security',
  },
  {
    id: 4,
    date: 'Today, 17 June',
    receivedImage: AnnaImage,
    receivedTitle: 'Received from Anna',
    receivedSum: '+$110',
    receivedCard: 'Debit •• 4385',
    receivedTotalSum: '$4,098.12',
    receivedDate: '17 June 2025, 17:49',
    receivedType: 'Payments',
  },
  {
    id: 5,
    date: 'Yesterday, 16 June',
    receivedImage: EarthImage,
    receivedTitle: 'See our limited offer!',
    subTitle: 'Would you like to visit new countries? Maybe it’s your time!',
    receivedDate: '16 June 2025, 23:08',
    receivedType: 'Travel',
    sentImage: TransferImage,
    sentTitle: 'Sent to •• 2041',
    sentSum: '-$14.62',
    sentCard: 'Debit •• 4385',
    sentTotalSum: '$3,987.5',
    sentDate: '16 June 2025, 06:18',
    sentType: 'Payments',
  },
  {
    id: 6,
    date: '24 March, 2025',
    receivedImage: ShieldImage,
    receivedTitle: 'New login into account',
    subTitle:
      'You have logged in from a new location:\niOS 26.0.1 · 109.255.84.7 · Spain',
    receivedDate: '24 March 2025, 15:44',
    receivedType: 'Security',
    isOnline: true,
  },
];
